### PR TITLE
Yarn v3

### PR DESCRIPTION
**Pull request by tiziodcaio**
I warn about you MUST enable corepack
- Node >= 16 --> corepack enable
- Node <= 15 --> npm install -g corepack; corepack enable

Have done after #370 

## Description

This PR tackles:

- Upgrade yarn from v1 to v3

## Checklist

- [X] I have followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md).
- [ ] The documentation related to the proposed change has been updated accordingly (plus comments in code). (not all, help needed)
- [X] I have written new tests for my core changes, as applicable.
- [X] I have successfully run tests with my changes locally.
- [X] It is ready for review! :rocket:

## Feature added

- Adding local caching (if you don't like this huge commit, I can remove local caching and make it slimmer)
- Update yarn from v1 to v3
- Adding corepack, so you don't have to push the yarn code into the repository always

### CODE REVIEW

**Comment by ImmuniDGR** [comment]
🚔 **Safety Check** 🚔

🔰 **Result** 🔰
- The following files have been modified: yarn.lock, package.json.
- The CircleCI configuration file has been modified.


⚠️ Some configuration files don't match the development branch. If you did not perform these changes, **please rebase on the development branch**.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #39678 (id: 4df7f9c1-9e2e-4b5b-b02b-b27308eec820)
- Last verified commit: 15b4a8b576504e09272364c7503c8b9d616b5209
- Time of check: 03/01/2022, 18:08:57 UTC
- The following protected files have been checked for changes: .editorconfig, .gitmodules, Gemfile, Gemfile.lock, app/build.gradle, app/proguard-rules.pro, build.gradle, ci/changelog\_config.tpl, ci/danger/commitlint/index.ts, ci/danger/commitlint/rules.ts, ci/danger/danger.ts, ci/danger/ktlint.ts, dangerfile.ts, fastlane/Appfile, fastlane/Fastfile, gradle.properties, gradlew, gradlew.bat, package.json, publiccode.yml, scheduler\_config.json, settings.gradle, template.properties, yarn.lock.

**Comment by valerio-castelli** [comment]
This change has broken the CI checks due to the inability to overwrite an already installed version of `corepack` @tiziodcaio. See [this failed CI job](https://app.circleci.com/pipelines/github/immuni-app/immuni-app-android/39707/workflows/e28dc90e-06f1-4654-bbb6-befe1037ff6e/jobs/40899) for reference. This is a little odd, though, since CircleCI's documentation about the `cimg/android:2021.10.2-node` Docker image states that it only includes Node 14.x. This is likely due to yarn already being installed in the image.

I'll update the CI to run `npm install -g corepack` with `--force`, but I'd ask you to double check that explicitly installing `corepack` is actually necessary at all.

**Comment by tiziodcaio** [comment]
I explain what corepack does
Yarn from v>1 decided to don't update the npm yarn, but it downloads directly into the .yarn folder a huge js file. In previous PRs someone has (correctly) not trusted my PR with this huge js file (which in fact was only downloaded using the  command yarn set version berry [codename for yarn v2/3]).
So after that I began to suggest the use of corepack, a package developed from the nodejs foundation that helps to override problems with the node pakage managers.
Pratically corepack downloads itself the yarn command from the repository, so I don't have to add the js yarn script to the PR.
If you have seen the package.json has got an add that tells to corepack wich package manager to use. To update or downgrade yarn simply change that version.

**Comment by valerio-castelli** [comment]
Thanks for the explanation, @tiziodcaio! I was just pointing out that using that syntax is causing the CI pipeline to fail pretty badly, due to `npm` refusing to overwrite the default `yarn` installation 🙂 

```
#!/bin/bash -eo pipefail
sudo npm i -g corepack; sudo corepack enable
[..................] / rollbackFailedOptional: verb npm-session 0a874f57ff2f500[[K..................] / rollbackFailedOptional: verb npm-session 0a874f57ff2f500[[K..................] / rollbackFailedOptional: verb npm-session 0a874f57ff2f500[[K..................] - rollbackFailedOptional: verb npm-session 0a874f57ff2f500[[K       ...........] | extract:corepack: verb lock using /root/.npm/_locks/stag/usr/local/bin/corepack -> /usr/local/lib/node_modules/corepack/dist/corepack.js
/usr/local/bin/pnpm -> /usr/local/lib/node_modules/corepack/dist/pnpm.js
/usr/local/bin/pnpx -> /usr/local/lib/node_modules/corepack/dist/pnpx.js
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/corepack/dist/yarn.js
npm ERR! dest /usr/local/bin/yarn
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/corepack/dist/yarn.js' -> '/usr/local/bin/yarn'
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-06T16_08_18_122Z-debug.log


Exited with code exit status 239
```

I'm waiting the next execution of the periodic CI job (which should happen in about one hour) to verify whether using `--force` is enough to restore the pipeline.

**Comment by tiziodcaio** [comment]
Maybe we can try removing the yarn default package and then adding corepack

**Comment by valerio-castelli** [comment]
In principle yes, we could, but it seems a bit more complex than necessary. Anyway, I've just verified that using the `--force` flag allows the CI to execute danger successfully, so I'd consider the problem resolved! 👍

**Comment by tiziodcaio** [comment]
Super!

**Comment by astagi** [comment]
Thank you @valerio-castelli @tiziodcaio

**Pull request merged**
