### PR TITLE
fix: Use the correct string for OTP verification

### PR DESCRIPTION
**Pull request by MartelliEnrico**
## Description

The string `upload_data_wait_operator_message` is used in the last card, where the string `upload_data_verify_message` should have been used. In fact this second string is not currently used anywhere.

## Checklist

- [x] I have followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md).
- [x] The documentation related to the proposed change has been updated accordingly (plus comments in code).
- [x] I have written new tests for my core changes, as applicable.
- [ ] I have successfully run tests with my changes locally.
- [ ] It is ready for review! :rocket:

### CODE REVIEW

**Comment by ImmuniDGR** [comment]
🚔 **Safety Check** 🚔

🔰 **Result** 🔰


✅ All configuration files are in line with the master branch.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #964 (id: 137575eb-91a0-4a8a-a14c-9e26fb8d7bab)
- Last verified commit: fb094054baef8c64b100261f9a7f38ecfa0140e8
- Time of check: 01/06/2020, 18:30:44 UTC
- The following protected files have been checked for changes: .editorconfig, .gitmodules, Gemfile, Gemfile.lock, app/build.gradle, app/proguard-rules.pro, build.gradle, ci/changelog\_config.tpl, ci/danger/commitlint/index.ts, ci/danger/commitlint/rules.ts, ci/danger/danger.ts, ci/danger/ktlint.ts, dangerfile.ts, fastlane/Appfile, fastlane/Fastfile, gradle.properties, gradlew, gradlew.bat, package.json, publiccode.yml, scheduler\_config.json, settings.gradle, template.properties, yarn.lock.

**Comment by ImmuniDGR** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Commitlint failed on the following commits (please do rebase): 

 - [fb094054baef8c64b100261f9a7f38ecfa0140e8] Use the correct string for OTP verification

The string `upload_data_wait_operator_message` is used in the last card, where the string `upload_data_verify_message` should have been used. In fact this second string is not currently used anywhere.
	- body's lines must not be longer than 100 characters
	- subject may not be empty
	- type may not be empty

Look at our rules and the [Conventional Commits](https://www.conventionalcommits.org) guidelines.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :white_check_mark: ktlint passed
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: ktlint passed
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: ktlint passed
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Thank you for submitting a pull request! The team will review your submission as soon as possible.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fb094054baef8c64b100261f9a7f38ecfa0140e8
</p>

**Review by marcouberti — APPROVED** [review]
Thanks.

**Comment by sebaker88** [comment]
@MartelliEnrico please reopen this PR against development branch. Thank you 🙏

**Pull request closed without merging**
