### PR TITLE
fix: Remove several unnecessary API Level checks

### PR DESCRIPTION
**Pull request by cortinico**
## Description

The codebase contains several unnecessary API Level checks
that are not needed as the `minSdkVersion` is set to 23.

This is a follow-up to @Datalux PRs #30
Please let me know if I should rebase on top of their branch

## Checklist

- [x] I have followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md).
- [x] I have successfully run tests with my changes locally.
- [x] It is ready for review! :rocket:

### CODE REVIEW

**Comment by ImmuniDGR** [comment]
🚔 **Safety Check** 🚔

🔰 **Result** 🔰


✅ All configuration files are in line with the master branch.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #137 (id: adb59fe0-ed52-4508-a742-081fb55812c9)
- Last verified commit: #6d996dde08c5e73406bf1909bba61b1300c1c9a2
- Time of check: 25/05/2020, 22:45:50 UTC
- The following protected files have been checked for changes: publiccode.yml, scheduler_config.json, ci/changelog_config.tpl, dangerfile.ts, ci/danger/ktlint.ts, fastlane/Appfile, settings.gradle, package.json, .editorconfig, Gemfile, ci/danger/commitlint/index.ts, template.properties, .gitmodules, gradlew.bat, gradlew, gradle.properties, Gemfile.lock, ci/danger/danger.ts, app/proguard-rules.pro, app/build.gradle, fastlane/Fastfile, ci/danger/commitlint/rules.ts, yarn.lock, build.gradle.

**Review by marcouberti — APPROVED** [review]

**Comment by cortinico** [comment]
up

**Comment by astagi** [comment]
@cortinico please reopen this PR against `development` branch. Thank you 🙏

**Comment by cortinico** [comment]
> @cortinico please reopen this PR against `development` branch. Thank you 🙏

Done 👍

**Pull request closed without merging**
