### PR TITLE
fix: remove deprecated getColor

### PR DESCRIPTION
**Pull request by Datalux**
Referred to #13 .

### CODE REVIEW

**Comment by eliseomartelli** [comment]
@Datalux Since it already happened to me: commits message should follow this: https://github.com/immuni-app/immuni-app-ios/blob/master/CONTRIBUTING.md#commits

**Comment by ImmuniDGR** [comment]
🚔 **Safety Check** 🚔

🔰 **Result** 🔰


✅ All configuration files are in line with the master branch.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #60 (id: a29a1f80-580b-46e6-98d5-19faa0cf4295)
- Last verified commit: #b37e918978f9949317e25645c67edcdaa423e524
- Time of check: 25/05/2020, 10:30:56 UTC
- The following protected files have been checked for changes: Gemfile.lock, template.properties, .gitmodules, package.json, fastlane/Fastfile, dangerfile.ts, .editorconfig, yarn.lock, build.gradle, gradle.properties, ci/danger/commitlint/rules.ts, ci/changelog_config.tpl, publiccode.yml, ci/danger/ktlint.ts, fastlane/Appfile, app/proguard-rules.pro, Gemfile, app/build.gradle, gradlew, ci/danger/commitlint/index.ts, scheduler_config.json, ci/danger/danger.ts, gradlew.bat, settings.gradle.

**Comment by sroddy** [comment]
Hi @Datalux, thanks a lot for your submission.

We have a `getColorCompat()` utility method as an extension to `Context`, in order to make the code a bit cleaner.

Can you please change your PR to use the method above, i.e.:

from
```kotlin
ContextCompat.getColor(context, R.color.transparent)
```

to
```kotlin
context.getColorCompat(R.color.transparent)
```

Also, there are already a couple of direct usages of the `ContextCompat.getColor()` method in the existing code. A quick lookup for `ContextCompat.getColor` in the code should highlight them. Can you please take care of fixing them too in this PR?

Thank you

**Comment by ImmuniDGR** [comment]
🚔 **Safety Check** 🚔

🔰 **Result** 🔰


✅ All configuration files are in line with the master branch.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #66 (id: 075f1269-002f-4ff2-9a20-69ad85963d62)
- Last verified commit: #414c3b119a20b4eb3c3ce7b49aed5ead1bab346c
- Time of check: 25/05/2020, 11:30:51 UTC
- The following protected files have been checked for changes: gradlew, scheduler_config.json, settings.gradle, fastlane/Appfile, Gemfile, Gemfile.lock, ci/danger/ktlint.ts, ci/danger/commitlint/index.ts, yarn.lock, ci/danger/commitlint/rules.ts, fastlane/Fastfile, .editorconfig, gradle.properties, ci/danger/danger.ts, .gitmodules, template.properties, app/proguard-rules.pro, gradlew.bat, build.gradle, app/build.gradle, dangerfile.ts, package.json, ci/changelog_config.tpl, publiccode.yml.

**Comment by Datalux** [comment]
@sroddy I have done!
I changed all `ContextCompat.getColor()` methods in `getColorCompat()`

**Comment by ImmuniDGR** [comment]
🚔 **Safety Check** 🚔

🔰 **Result** 🔰


✅ All configuration files are in line with the master branch.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #460 (id: d5f8195e-1048-4497-954f-77c20963ffd8)
- Last verified commit: #8ed81115aa63de5a42d81de3c4db3b34faf98d1d
- Time of check: 28/05/2020, 13:30:38 UTC
- The following protected files have been checked for changes: template.properties, fastlane/Fastfile, gradlew.bat, ci/danger/danger.ts, package.json, gradlew, ci/danger/commitlint/index.ts, publiccode.yml, build.gradle, app/build.gradle, ci/danger/ktlint.ts, .editorconfig, ci/danger/commitlint/rules.ts, yarn.lock, Gemfile, ci/changelog_config.tpl, fastlane/Appfile, .gitmodules, gradle.properties, scheduler_config.json, dangerfile.ts, app/proguard-rules.pro, settings.gradle, Gemfile.lock.

**Comment by ImmuniDGR** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Commitlint failed on the following commits (please do rebase): 

 - [b37e918978f9949317e25645c67edcdaa423e524] fixes issue #13
	- subject may not be empty
	- type may not be empty

Look at our rules and the [Conventional Commits](https://www.conventionalcommits.org) guidelines.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :white_check_mark: ktlint passed
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: ktlint passed
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: ktlint passed
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Thank you for submitting a pull request! The team will review your submission as soon as possible.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b292ffc3aa8c837a5e79907b57ffe23d3736d09a
</p>

**Review by marcouberti — APPROVED** [review]

**Pull request closed without merging**
