### PR TITLE
Feature/Yarn v3

### PR DESCRIPTION
**Pull request by tiziodcaio**
I warn about you MUST enable corepack
- Node >= 16 --> corepack enable
- Node <= 15 --> npm install -g corepack; corepack enable
If you prefer, we can remove caching. More infos at https://yarnpkg.com/

## Description

This PR tackles:

- ...
- ...
- ...

In particular, the ...

## Checklist

- [X] I have followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md).
- [ ] The documentation related to the proposed change has been updated accordingly (plus comments in code). (not all, help needed)
- [X] I have written new tests for my core changes, as applicable.
- [X] I have successfully run tests with my changes locally.
- [X] It is ready for review! :rocket:

## Feature added

- Adding local caching (if you don't like this huge commit, I can remove local caching and make it slimmer)
- Update yarn from v1 to v3
- Adding corepack, so you don't have to push the yarn code into the repository always

### CODE REVIEW

**Comment by ImmuniDGR** [comment]
🚔 **Safety Check** 🚔

🔰 **Result** 🔰
- The following files have been modified: yarn.lock, package.json.
- The CircleCI configuration file has been modified.


⚠️ Some configuration files don't match the development branch. If you did not perform these changes, **please rebase on the development branch**.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #39333 (id: 454c985c-1912-46af-abe9-300212552e01)
- Last verified commit: 78ea3ca9a25c1e51be04a06e400a603edac68498
- Time of check: 07/12/2021, 12:10:19 UTC
- The following protected files have been checked for changes: .editorconfig, .gitmodules, Gemfile, Gemfile.lock, app/build.gradle, app/proguard-rules.pro, build.gradle, ci/changelog\_config.tpl, ci/danger/commitlint/index.ts, ci/danger/commitlint/rules.ts, ci/danger/danger.ts, ci/danger/ktlint.ts, dangerfile.ts, fastlane/Appfile, fastlane/Fastfile, gradle.properties, gradlew, gradlew.bat, package.json, publiccode.yml, scheduler\_config.json, settings.gradle, template.properties, yarn.lock.

**Comment by astagi** [comment]
@tiziodcaio yarn cache is not gitignored

**Comment by tiziodcaio** [comment]
> @tiziodcaio yarn cache is not gitignored

The cache can be included in the git repository, as said in the documentation. If you prefer lighter git commits, I can close this PR and make an other with the cache gitignored

**Comment by tiziodcaio** [comment]
And so? What should we do @astagi

**Comment by astagi** [comment]
Hi @tiziodcaio sorry I'm not 100% available during these days! I'd love to upgrade Yarn to V3 and I understand what yarn cache brings to users but I prefer a lighter PR.

**Comment by tiziodcaio** [comment]
Sure! I will proceed as soon I can

**Comment by astagi** [comment]
> Sure! I will proceed as soon I can

Thank you!

**Comment by tiziodcaio** [comment]
Please see #377

**Pull request closed without merging**
