### PR TITLE
feat: disable screenshots to preserve privacy

### PR DESCRIPTION
**Pull request by marcouberti**
## Description

For privacy reason we prevent the users to take screenshots.

## Checklist

- [x] I have followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md).
- [x] The documentation related to the proposed change has been updated accordingly (plus comments in code).
- [ ] I have written new tests for my core changes, as applicable.
- [x] I have successfully run tests with my changes locally.
- [x] It is ready for review! :rocket:

### CODE REVIEW

**Comment by mlocati** [comment]
Out of curiosity, which is the sensitive displayed data that shouldn't be copied/shared?

**Comment by ImmuniDGR** [comment]
🚔 **Safety Check** 🚔

🔰 **Result** 🔰


✅ All configuration files are in line with the master branch.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #224 (id: 3e6fdf1e-29bf-4eb4-af29-a01a7f4226a7)
- Last verified commit: #ce81c699c36d6babcef6082e0803680660294e47
- Time of check: 26/05/2020, 16:01:47 UTC
- The following protected files have been checked for changes: build.gradle, app/build.gradle, fastlane/Fastfile, yarn.lock, settings.gradle, Gemfile.lock, .editorconfig, ci/danger/commitlint/index.ts, app/proguard-rules.pro, package.json, publiccode.yml, gradlew, ci/danger/danger.ts, Gemfile, template.properties, ci/changelog_config.tpl, gradle.properties, .gitmodules, ci/danger/ktlint.ts, gradlew.bat, ci/danger/commitlint/rules.ts, fastlane/Appfile, scheduler_config.json, dangerfile.ts.

**Comment by marcouberti** [comment]
@mlocati when the app goes background the system generate a screenshot automatically to show it in the recent tasks. In this screenshot we can potentially have the OTP code or the information about a possible exposure or a COVID-9 positive state. We want to prevent possible leaks in this scenario.

**Comment by mlocati** [comment]
Thanks for the detailed and quick answer

**Pull request merged**
